//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LibraMPTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LIBRAMPTOOL_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PORT_SETTING         129
#define IDB_BITMAP_DISK_SCAN            130
#define IDB_BITMAP_DISK_NULL            131
#define IDB_BITMAP_DISK_NORMAL          132
#define IDB_BITMAP_DISK_INFO            133
#define IDB_BITMAP_DISK_RUNNING         134
#define IDB_BITMAP_DISK_SUCCESS         135
#define IDB_BITMAP_DISK_FAIL            136
#define IDD_DIALOG_MP_INFO              137
#define IDD_DIALOG1                     138
#define IDD_DIALOG_PARAMETER            138
#define IDD_DIALOG_PASSWORD             139
#define IDD_DIALOG_CREATE               140
#define IDC_BUTTON_RESCAN               1000
#define IDC_CHECK_DISK_1                1001
#define IDC_CHECK_DISK_2                1002
#define IDC_CHECK_DISK_3                1003
#define IDC_CHECK_DISK_4                1004
#define IDC_CHECK_DISK_5                1005
#define IDC_CHECK_DISK_6                1006
#define IDC_CHECK_DISK_7                1007
#define IDC_CHECK_DISK_8                1008
#define IDC_STATIC_SN_1                 1009
#define IDC_STATIC_SN_2                 1010
#define IDC_STATIC_SN_3                 1011
#define IDC_STATIC_SN_4                 1012
#define IDC_STATIC_SN_5                 1013
#define IDC_STATIC_SN_6                 1014
#define IDC_STATIC_SN_7                 1015
#define IDC_STATIC_SN_8                 1016
#define IDC_EDIT_SN_PORT_0              1017
#define IDC_EDIT_SN_PORT_1              1018
#define IDC_EDIT_SN_PORT_2              1019
#define IDC_EDIT_SN_PORT_3              1020
#define IDC_EDIT_SN_PORT_4              1021
#define IDC_EDIT_SN_PORT_5              1022
#define IDC_EDIT_SN_PORT_6              1023
#define IDC_EDIT_SN_PORT_7              1024
#define IDC_STATIC_DISK_1               1025
#define IDC_STATIC_DISK_2               1026
#define IDC_STATIC_DISK_3               1027
#define IDC_STATIC_DISK_4               1028
#define IDC_STATIC_DISK_5               1029
#define IDC_STATIC_DISK_6               1030
#define IDC_STATIC_DISK_7               1031
#define IDC_STATIC_DISK_8               1032
#define IDC_TAB_CONTENT                 1033
#define IDC_STATIC_PORT_1               1034
#define IDC_STATIC_SN_PORT_1            1034
#define IDC_STATIC_PORT_2               1035
#define IDC_STATIC_SN_PORT_2            1035
#define IDC_STATIC_PORT_3               1036
#define IDC_STATIC_SN_PORT_3            1036
#define IDC_STATIC_PORT_4               1037
#define IDC_STATIC_SN_PORT_4            1037
#define IDC_STATIC_PORT_5               1038
#define IDC_STATIC_SN_PORT_5            1038
#define IDC_STATIC_PORT_6               1039
#define IDC_STATIC_SN_PORT_6            1039
#define IDC_STATIC_PORT_7               1040
#define IDC_STATIC_SN_PORT_7            1040
#define IDC_STATIC_PORT_8               1041
#define IDC_STATIC_SN_PORT_8            1041
#define IDC_PROGRESS_PORT_1             1042
#define IDC_PROGRESS_PORT_2             1043
#define IDC_PROGRESS_PORT_3             1044
#define IDC_PROGRESS_PORT_4             1045
#define IDC_PROGRESS_PORT_5             1046
#define IDC_PROGRESS_PORT_6             1047
#define IDC_PROGRESS_PORT_7             1048
#define IDC_PROGRESS_PORT_8             1049
#define IDC_STATIC_INFO_PORT_1          1052
#define IDC_STATIC_INFO_PORT_2          1053
#define IDC_STATIC_INFO_PORT_3          1054
#define IDC_STATIC_INFO_PORT_4          1055
#define IDC_STATIC_INFO_PORT_5          1056
#define IDC_STATIC_INFO_PORT_6          1057
#define IDC_STATIC_INFO_PORT_7          1058
#define IDC_STATIC_INFO_PORT_8          1059
#define IDC_COMBO_CONFIG_LIST           1060
#define IDC_STATIC_FW_MODE_PORT_1       1061
#define IDC_STATIC_FW_MODE_PORT_2       1062
#define IDC_STATIC_FW_MODE_PORT_3       1063
#define IDC_STATIC_FW_MODE_PORT_4       1064
#define IDC_STATIC_FW_MODE_PORT_5       1065
#define IDC_STATIC_FW_MODE_PORT_6       1066
#define IDC_STATIC_FW_MODE_PORT_7       1067
#define IDC_STATIC_FW_MODE_PORT_8       1068
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_1 1069
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_2 1070
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_3 1071
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_4 1072
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_5 1073
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_6 1074
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_7 1075
#define IDC_STATIC_PHYSICAL_ADDRESS_PORT_8 1076
#define IDC_BUTTON_SAVE_AS              1077
#define IDOK_EDIT                       1078
#define IDCANCEL_SAVE                   1079
#define IDC_EDIT_BEGIN_SN               1080
#define IDC_EDIT_END_SN                 1081
#define IDC_EDIT_SN_MASK                1082
#define IDC_EDIT_INFO_PORT_1            1083
#define IDC_EDIT_INFO_PORT_2            1084
#define IDC_EDIT_INFO_PORT_3            1085
#define IDC_EDIT_INFO_PORT_4            1086
#define IDC_EDIT_INFO_PORT_5            1087
#define IDC_EDIT_INFO_PORT_6            1088
#define IDC_EDIT_INFO_PORT_7            1089
#define IDC_EDIT_INFO_PORT_8            1090
#define IDC_STATIC_TIMER_PORT_1         1092
#define IDC_STATIC_TIMER_PORT_2         1093
#define IDC_STATIC_TIMER_PORT_3         1094
#define IDC_STATIC_TIMER_PORT_4         1095
#define IDC_STATIC_TIMER_PORT_5         1096
#define IDC_STATIC_TIMER_PORT_6         1097
#define IDC_STATIC_TIMER_PORT_7         1098
#define IDC_STATIC_TIMER_PORT_8         1099
#define IDC_EDIT_NVME_VID               1100
#define IDC_EDIT_NVME_DID               1101
#define IDC_EDIT_SYS_EUI64              1102
#define IDC_EDIT_NVME_MN                1103
#define IDC_EDIT_SYS_FW_VERSION         1104
#define IDC_EDIT_PASSWORD               1105
#define IDC_STATIC_TEST_RESULT          1107
#define IDC_COMBO_NVME_CAPACITY         1108
#define IDC_EDIT_NVME_CAPACITY_MANUAL   1109
#define IDC_LIST_PARAMETER              1110
#define IDC_BUTTON_CREATE               1111
#define IDC_EDIT_PARAMETER              1112
#define IDC_EDIT_CONFIG_FILE_NAME       1113
#define IDC_EDIT_CONFIG_TYPE            1114
#define IDC_CHECK_RDT                   1115
#define IDC_EDIT_BIN_PATH               1116
#define IDC_LIST_MP_PARAMETER           1117
#define IDC_EDIT1                       1118
#define IDC_EDIT_MP_PARAMETER           1118

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
